services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "5001:5001"
    restart: unless-stopped
    depends_on:
      - backend
